language: php

php:
    - '7.1'
    - '7.2'
    - nightly

ignore:
    - README.md
    - .gitignore

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_script: composer install

script: phpunit